# Generated by Django 3.0.4 on 2020-03-31 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0002_auto_20200331_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='group_id',
        ),
        migrations.AddField(
            model_name='event',
            name='sentry_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crashes.EventGroup'),
            preserve_default=False,
        ),
    ]
