# Generated by Django 3.0.4 on 2020-03-31 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0003_auto_20200331_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtag',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventtag',
            name='value',
        ),
        migrations.CreateModel(
            name='EventTagKeyed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('event_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crashes.EventTag')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='crashes.EventTagKeyed'),
        ),
    ]
