# Generated by Django 3.2.5 on 2021-07-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0004_auto_20200331_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcategory',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterUniqueTogether(
            name='eventtagkeyed',
            unique_together={('event_tag', 'value')},
        ),
    ]
