# Generated by Django 3.2.5 on 2021-07-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0005_auto_20210719_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedcategory',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.AddField(
            model_name='assignedcategory',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crashes.eventgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='categories',
            field=models.ManyToManyField(through='crashes.AssignedCategory', to='crashes.Category'),
        ),
    ]
