# Generated by Django 3.2.5 on 2021-07-20 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_created']},
        ),
    ]
