# Generated by Django 3.2.5 on 2021-07-22 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0010_stacktrace_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('events_project_name', models.CharField(max_length=512)),
                ('events_endpoint_template', models.CharField(max_length=1024, unique=True)),
                ('token', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crashes.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crashes.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crashes.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtag',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crashes.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtagkeyed',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crashes.project'),
            preserve_default=False,
        ),
    ]
