# Generated by Django 3.2.5 on 2021-07-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0011_auto_20210722_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='events_endpoint_template',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
