# Generated by Django 3.2.5 on 2021-07-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0012_auto_20210722_2324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('project', 'sentry_id')},
        ),
        migrations.AlterUniqueTogether(
            name='eventgroup',
            unique_together={('project', 'group_id')},
        ),
        migrations.AlterUniqueTogether(
            name='eventtag',
            unique_together={('project', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='eventtagkeyed',
            unique_together={('project', 'event_tag', 'value')},
        ),
    ]
