# Generated by Django 3.2.5 on 2021-07-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0014_auto_20210723_2302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedcategory',
            unique_together={('group', 'category')},
        ),
    ]
