# Generated by Django 3.2.5 on 2021-07-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0015_alter_assignedcategory_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField()),
                ('days_back', models.IntegerField()),
                ('is_info', models.BooleanField()),
                ('trend', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crashes.category')),
            ],
        ),
    ]
