# Generated by Django 3.2.5 on 2021-08-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0017_auto_20210727_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='events_endpoint_template',
            new_name='events_endpoint',
        ),
        migrations.RemoveField(
            model_name='project',
            name='events_project_name',
        ),
        migrations.AlterUniqueTogether(
            name='categorycounts',
            unique_together={('category', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='computedtrend',
            unique_together={('category', 'for_date', 'days_back')},
        ),
    ]
