# Generated by Django 3.2.5 on 2021-08-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0018_auto_20210806_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryCounts',
            new_name='CategoryCount',
        ),
    ]
