# Generated by Django 3.2.5 on 2021-08-06 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0020_projectendpointcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectendpointcache',
            name='sample_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
