# Generated by Django 3.2.5 on 2021-08-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0021_projectendpointcache_sample_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectendpointcache',
            name='processed',
        ),
    ]
