# Generated by Django 3.2.5 on 2021-08-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0023_auto_20210812_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='message',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
