# Generated by Django 3.2.5 on 2021-08-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0026_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycount',
            name='keyed_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crashes.eventtagkeyed'),
        ),
        migrations.AddField(
            model_name='computedtrend',
            name='keyed_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crashes.eventtagkeyed'),
        ),
        migrations.AlterUniqueTogether(
            name='computedtrend',
            unique_together={('keyed_tag', 'category', 'for_date', 'days_back')},
        ),
    ]
