# Generated by Django 3.2.5 on 2021-08-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0027_auto_20210812_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessEventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crashes.eventtag')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crashes.project')),
            ],
        ),
    ]
